
export const countries = [
      { "code": "AF", "alpha3code": "AFG", "prefix": "93", "name": "Afghanistan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AB", "alpha3code": "ABK", "prefix": "7840", "name": "Abkhazia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AB", "alpha3code": "ABK", "prefix": "7940", "name": "Abkhazia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AX", "alpha3code": "ALA", "prefix": "35818", "name": "Aland Inland", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "AL", "alpha3code": "ALB", "prefix": "355", "name": "Albania", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "DZ", "alpha3code": "DZA", "prefix": "213", "name": "Algeria", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AS", "alpha3code": "ASM", "prefix": "684", "name": "American Samoa", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AD", "alpha3code": "AND", "prefix": "376", "name": "Andorra", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AO", "alpha3code": "AGO", "prefix": "244", "name": "Angola", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AI", "alpha3code": "AIA", "prefix": "1264", "name": "Anguilla", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AQ", "alpha3code": "ATA", "prefix": "672", "name": "Antarctica", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AG", "alpha3code": "ATG", "prefix": "1268", "name": "Antigua And Barbuda", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AR", "alpha3code": "ARG", "prefix": "54", "name": "Argentina", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AM", "alpha3code": "ARM", "prefix": "374", "name": "Armenia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AW", "alpha3code": "ABW", "prefix": "297", "name": "Aruba", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AC", "alpha3code": "ACI", "prefix": "247", "name": "Ascension Island", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AU", "alpha3code": "AUS", "prefix": "61", "name": "Australia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AT", "alpha3code": "AUT", "prefix": "43", "name": "Austria", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "20.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "AZ", "alpha3code": "AZE", "prefix": "994", "name": "Azerbaijan", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BS", "alpha3code": "BHS", "prefix": "1242", "name": "Bahamas", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BH", "alpha3code": "BHR", "prefix": "973", "name": "Bahrain", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BD", "alpha3code": "BGD", "prefix": "880", "name": "Bangladesh", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BB", "alpha3code": "BRB", "prefix": "1246", "name": "Barbados", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BY", "alpha3code": "BLR", "prefix": "375", "name": "Belarus", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BE", "alpha3code": "BEL", "prefix": "32", "name": "Belgium", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "21.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "BZ", "alpha3code": "BLZ", "prefix": "501", "name": "Belize", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BJ", "alpha3code": "BEN", "prefix": "229", "name": "Benin", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BM", "alpha3code": "BMU", "prefix": "1441", "name": "Bermuda", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BT", "alpha3code": "BTN", "prefix": "975", "name": "Bhutan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BO", "alpha3code": "BOL", "prefix": "591", "name": "Bolivia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BA", "alpha3code": "BIH", "prefix": "387", "name": "Bosnia And Herzegovina", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BW", "alpha3code": "BWA", "prefix": "267", "name": "Botswana", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BR", "alpha3code": "BRA", "prefix": "55", "name": "Brazil", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IO", "alpha3code": "IOT", "prefix": "1246", "name": "British Indian Ocean Territory", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "VG", "alpha3code": "VGB", "prefix": "1284", "name": "British Virgin Islands", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IB", "alpha3code": "ICO", "prefix": "8810", "name": "ICO (SAT)", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IB", "alpha3code": "ICO", "prefix": "8811", "name": "ICO (SAT)", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BN", "alpha3code": "BRN", "prefix": "673", "name": "Brunei", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BG", "alpha3code": "BGR", "prefix": "359", "name": "Bulgaria", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "20.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "BF", "alpha3code": "BFA", "prefix": "226", "name": "Burkina Faso", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "BI", "alpha3code": "BDI", "prefix": "257", "name": "Burundi", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KH", "alpha3code": "KHM", "prefix": "855", "name": "Cambodia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CM", "alpha3code": "CMR", "prefix": "237", "name": "Cameroon", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CA", "alpha3code": "CAN", "prefix": "1", "name": "Canada", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CV", "alpha3code": "CPV", "prefix": "238", "name": "Cape Verde", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KY", "alpha3code": "CYM", "prefix": "1345", "name": "Cayman Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CF", "alpha3code": "CAF", "prefix": "236", "name": "Central African Republic", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TD", "alpha3code": "TCD", "prefix": "235", "name": "Chad", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TA", "alpha3code": "TAS", "prefix": "3732", "name": "Transnistria", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TA", "alpha3code": "TAS", "prefix": "3735", "name": "Transnistria", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CL", "alpha3code": "CHL", "prefix": "56", "name": "Chile", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CN", "alpha3code": "CHN", "prefix": "86", "name": "China", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CX", "alpha3code": "CXR", "prefix": "618", "name": "Christmas Island", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CC", "alpha3code": "CCK", "prefix": "61", "name": "Cocos (Keeling) Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CO", "alpha3code": "COL", "prefix": "57", "name": "Colombia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KM", "alpha3code": "COM", "prefix": "269", "name": "Comoros", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CG", "alpha3code": "COG", "prefix": "242", "name": "Congo", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CD", "alpha3code": "COD", "prefix": "243", "name": "Congo DR", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CK", "alpha3code": "COK", "prefix": "682", "name": "Cook Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CR", "alpha3code": "CRI", "prefix": "506", "name": "Costa Rica", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CI", "alpha3code": "CIV", "prefix": "225", "name": "Cote d'Ivoire", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "HR", "alpha3code": "HRV", "prefix": "385", "name": "Croatia", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "25.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "CU", "alpha3code": "CUB", "prefix": "53", "name": "Cuba", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "CY", "alpha3code": "CYP", "prefix": "357", "name": "Cyprus", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "19.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "CZ", "alpha3code": "CZE", "prefix": "420", "name": "Czech Republic", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "21.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "DK", "alpha3code": "DNK", "prefix": "45", "name": "Denmark", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "25.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "DI", "alpha3code": "DIR", "prefix": "888", "name": "Disaster Relief", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "25.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "IG", "alpha3code": "IGA", "prefix": "246", "name": "Diego Garcia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "DJ", "alpha3code": "DJI", "prefix": "253", "name": "Djibouti", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "DM", "alpha3code": "DMA", "prefix": "1767", "name": "Dominica", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "DO", "alpha3code": "DOM", "prefix": "1809", "name": "Dominican Republic", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "EC", "alpha3code": "ECU", "prefix": "593", "name": "Ecuador", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "EL", "alpha3code": "ELO", "prefix": "8812", "name": "Ellipso (SAT)", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "EL", "alpha3code": "ELO", "prefix": "8813", "name": "Ellipso (SAT)", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "EG", "alpha3code": "EGY", "prefix": "20", "name": "Egypt", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SV", "alpha3code": "SLV", "prefix": "503", "name": "El Salvador", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "EM", "alpha3code": "EMS", "prefix": "88213", "name": "EMSAT", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GQ", "alpha3code": "GNQ", "prefix": "240", "name": "Equatorial Guinea", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ER", "alpha3code": "ERI", "prefix": "291", "name": "Eritrea", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "EE", "alpha3code": "EST", "prefix": "372", "name": "Estonia", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "20.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "ET", "alpha3code": "ETH", "prefix": "251", "name": "Ethiopia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "FK", "alpha3code": "FLK", "prefix": "500", "name": "Falkland Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "FO", "alpha3code": "FRO", "prefix": "298", "name": "Faroe Islands", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "FJ", "alpha3code": "FJI", "prefix": "679", "name": "Fiji", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "FI", "alpha3code": "FIN", "prefix": "358", "name": "Finland", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "24.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "FR", "alpha3code": "FRA", "prefix": "33", "name": "France", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "20.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "GF", "alpha3code": "GUF", "prefix": "596", "name": "French Guiana", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "PF", "alpha3code": "PYF", "prefix": "594", "name": "French Polynesia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TF", "alpha3code": "ATF", "prefix": "689", "name": "French Southern Territories", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GA", "alpha3code": "GAB", "prefix": "241", "name": "Gabon", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GM", "alpha3code": "GMB", "prefix": "220", "name": "Gambia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GE", "alpha3code": "GEO", "prefix": "995", "name": "Georgia", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "DE", "alpha3code": "DEU", "prefix": "49", "name": "Germany", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "19.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "GH", "alpha3code": "GHA", "prefix": "233", "name": "Ghana", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GI", "alpha3code": "GIB", "prefix": "350", "name": "Gibraltar", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "GO", "alpha3code": "GOS", "prefix": "1", "name": "Global Mobile Satellite System", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GS", "alpha3code": "GST", "prefix": "881", "name": "Globalstar", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GS", "alpha3code": "GST", "prefix": "8818", "name": "Globalstar", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GS", "alpha3code": "GST", "prefix": "8819", "name": "Globalstar", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GR", "alpha3code": "GRC", "prefix": "30", "name": "Greece", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "24.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "GL", "alpha3code": "GRL", "prefix": "299", "name": "Greenland", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GD", "alpha3code": "GRD", "prefix": "1473", "name": "Grenada", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GP", "alpha3code": "GLP", "prefix": "590", "name": "Guadeloupe", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "GU", "alpha3code": "GUM", "prefix": "1671", "name": "Guam", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GT", "alpha3code": "GTM", "prefix": "502", "name": "Guatemala", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GG", "alpha3code": "GGY", "prefix": "441481", "name": "Guernsey", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "GN", "alpha3code": "GIN", "prefix": "224", "name": "Guinea", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GW", "alpha3code": "GNB", "prefix": "245", "name": "Guinea-Bissau", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GY", "alpha3code": "GUY", "prefix": "592", "name": "Guyana", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "HT", "alpha3code": "HTI", "prefix": "509", "name": "Haiti", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "HN", "alpha3code": "HND", "prefix": "504", "name": "Honduras", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "HK", "alpha3code": "HKG", "prefix": "852", "name": "Hong Kong", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "HU", "alpha3code": "HUN", "prefix": "36", "name": "Hungary", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "27.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "IS", "alpha3code": "ISL", "prefix": "354", "name": "Iceland", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "IN", "alpha3code": "IND", "prefix": "91", "name": "India", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ID", "alpha3code": "IDN", "prefix": "62", "name": "Indonesia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IU", "alpha3code": "IUT", "prefix": "870", "name": "Inmarsat", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IA", "alpha3code": "IAT", "prefix": "88241", "name": "INSAT", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "FF", "alpha3code": "FFS", "prefix": "1", "name": "International Freephone Service", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "XA", "alpha3code": "XAI", "prefix": "882", "name": "International Networks1", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "XB", "alpha3code": "XAI", "prefix": "883", "name": "International Networks2", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IP", "alpha3code": "IPR", "prefix": "1", "name": "International Premium Rate Service", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "II", "alpha3code": "IIM", "prefix": "8816", "name": "Iridium (SAT)", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "II", "alpha3code": "IIM", "prefix": "8817", "name": "Iridium (SAT)", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IC", "alpha3code": "ICS", "prefix": "1", "name": "International Shared Cost Service", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IR", "alpha3code": "IRN", "prefix": "98", "name": "Iran", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "Y" },
      { "code": "IQ", "alpha3code": "IRQ", "prefix": "964", "name": "Iraq", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IE", "alpha3code": "IRL", "prefix": "353", "name": "Ireland", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "23.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "IM", "alpha3code": "IMN", "prefix": "441624", "name": "Isle of Man", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "IL", "alpha3code": "ISR", "prefix": "972", "name": "Israel", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "IT", "alpha3code": "ITA", "prefix": "39", "name": "Italy", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "22.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "JM", "alpha3code": "JAM", "prefix": "1876", "name": "Jamaica", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "JP", "alpha3code": "JPN", "prefix": "81", "name": "Japan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "JE", "alpha3code": "JEY", "prefix": "441534", "name": "Jersey", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "JT", "alpha3code": "JTE", "prefix": "88236", "name": "Jersey Telecom", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "Y" },
      { "code": "JO", "alpha3code": "JOR", "prefix": "962", "name": "Jordan", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KZ", "alpha3code": "KAZ", "prefix": "7", "name": "Kazakhstan", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KE", "alpha3code": "KEN", "prefix": "254", "name": "Kenya", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KI", "alpha3code": "KIR", "prefix": "686", "name": "Kiribati", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KW", "alpha3code": "KWT", "prefix": "965", "name": "Kuwait", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KG", "alpha3code": "KGZ", "prefix": "996", "name": "Kyrgyzstan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "XK", "alpha3code": "KOS", "prefix": "383", "name": "Kosovo", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LA", "alpha3code": "LAO", "prefix": "856", "name": "Laos", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LV", "alpha3code": "LVA", "prefix": "371", "name": "Latvia", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "21.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "LB", "alpha3code": "LBN", "prefix": "961", "name": "Lebanon", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LS", "alpha3code": "LSO", "prefix": "266", "name": "Lesotho", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LR", "alpha3code": "LBR", "prefix": "231", "name": "Liberia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LY", "alpha3code": "LBY", "prefix": "218", "name": "Libyan Arab Jamahiriya", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LI", "alpha3code": "LIE", "prefix": "423", "name": "Liechtenstein", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "LT", "alpha3code": "LTU", "prefix": "370", "name": "Lithuania", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "21.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "LU", "alpha3code": "LUX", "prefix": "352", "name": "Luxembourg", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "17.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "MO", "alpha3code": "MAC", "prefix": "853", "name": "Macao", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MK", "alpha3code": "MKD", "prefix": "389", "name": "Macedonia ", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MG", "alpha3code": "MDG", "prefix": "261", "name": "Madagascar", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MW", "alpha3code": "MWI", "prefix": "265", "name": "Malawi", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MY", "alpha3code": "MYS", "prefix": "60", "name": "Malaysia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MV", "alpha3code": "MDV", "prefix": "960", "name": "Maldives", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ML", "alpha3code": "MLI", "prefix": "223", "name": "Mali", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MT", "alpha3code": "MLT", "prefix": "356", "name": "Malta", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "18.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "MI", "alpha3code": "MIS", "prefix": "1", "name": "Maritime Mobile Service Applications", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MH", "alpha3code": "MHL", "prefix": "692", "name": "Marshall islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MQ", "alpha3code": "MTQ", "prefix": "596", "name": "Martinique", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "MR", "alpha3code": "MRT", "prefix": "222", "name": "Mauritania", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MU", "alpha3code": "MUS", "prefix": "230", "name": "Mauritius", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "YT", "alpha3code": "MYT", "prefix": "269", "name": "Mayotte", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "MX", "alpha3code": "MEX", "prefix": "52", "name": "Mexico", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "FM", "alpha3code": "FSM", "prefix": "691", "name": "Micronesia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MD", "alpha3code": "MDA", "prefix": "373", "name": "Moldova", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MC", "alpha3code": "MCO", "prefix": "377", "name": "Monaco", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "MN", "alpha3code": "MNG", "prefix": "976", "name": "Mongolia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ME", "alpha3code": "MNE", "prefix": "382", "name": "Montenegro", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MS", "alpha3code": "MSR", "prefix": "1664", "name": "Montserrat", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MA", "alpha3code": "MAR", "prefix": "212", "name": "Morocco", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MZ", "alpha3code": "MOZ", "prefix": "258", "name": "Mozambique", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "MM", "alpha3code": "MMR", "prefix": "95", "name": "Myanmar", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NA", "alpha3code": "NAM", "prefix": "264", "name": "Namibia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NR", "alpha3code": "NRU", "prefix": "674", "name": "Nauru", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NP", "alpha3code": "NPL", "prefix": "977", "name": "Nepal", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NL", "alpha3code": "NLD", "prefix": "31", "name": "Netherlands", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "21.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "AN", "alpha3code": "ANT", "prefix": "599", "name": "Netherlands Antilles", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NC", "alpha3code": "NCL", "prefix": "687", "name": "New Caledonia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NZ", "alpha3code": "NZL", "prefix": "64", "name": "New Zealand", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NI", "alpha3code": "NIC", "prefix": "505", "name": "Nicaragua", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NE", "alpha3code": "NER", "prefix": "227", "name": "Niger", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NG", "alpha3code": "NGA", "prefix": "234", "name": "Nigeria", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NU", "alpha3code": "NIU", "prefix": "683", "name": "Niue", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NF", "alpha3code": "NFK", "prefix": "672", "name": "Norfolk Island", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NN", "alpha3code": "NNP", "prefix": "1", "name": "North American Numbering Plan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KP", "alpha3code": "PRK", "prefix": "850", "name": "North Korea", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "Y" },
      { "code": "MP", "alpha3code": "MNP", "prefix": "1670", "name": "Northern Mariana Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "NO", "alpha3code": "NOR", "prefix": "47", "name": "Norway", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "OM", "alpha3code": "OMN", "prefix": "968", "name": "Oman", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "OR", "alpha3code": "ORA", "prefix": "88233", "name": "Oration", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PK", "alpha3code": "PAK", "prefix": "92", "name": "Pakistan", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PW", "alpha3code": "PLW", "prefix": "680", "name": "Palau", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PS", "alpha3code": "PSE", "prefix": "970", "name": "Palestine", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PA", "alpha3code": "PAN", "prefix": "507", "name": "Panama", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PG", "alpha3code": "PNG", "prefix": "675", "name": "Papua New Guinea", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PY", "alpha3code": "PRY", "prefix": "595", "name": "Paraguay", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PE", "alpha3code": "PER", "prefix": "51", "name": "Peru", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PH", "alpha3code": "PHL", "prefix": "63", "name": "Philippines", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PL", "alpha3code": "POL", "prefix": "48", "name": "Poland", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "23.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "PT", "alpha3code": "PRT", "prefix": "351", "name": "Portugal", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "23.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "PR", "alpha3code": "PRI", "prefix": "1787", "name": "Puerto Rico", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "QA", "alpha3code": "QAT", "prefix": "974", "name": "Qatar", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "RI", "alpha3code": "RIC", "prefix": "878", "name": "Reservation currently under investigatigation", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "RG", "alpha3code": "RGS", "prefix": "1", "name": "Reserved for future global service", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "RE", "alpha3code": "REU", "prefix": "262", "name": "Reunion", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "RO", "alpha3code": "ROU", "prefix": "40", "name": "Romania", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "19.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "RU", "alpha3code": "RUS", "prefix": "7", "name": "Russia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "RW", "alpha3code": "RWA", "prefix": "250", "name": "Rwanda", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SH", "alpha3code": "SHN", "prefix": "290", "name": "Saint Helena", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "WS", "alpha3code": "WSM", "prefix": "685", "name": "Samoa", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SM", "alpha3code": "SMR", "prefix": "378", "name": "San Marino", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "ST", "alpha3code": "STP", "prefix": "239", "name": "Sao Tome and Principe", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SA", "alpha3code": "SAU", "prefix": "966", "name": "Saudi Arabia", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SN", "alpha3code": "SEN", "prefix": "221", "name": "Senegal", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "RS", "alpha3code": "SRB", "prefix": "381", "name": "Serbia", "iban": "R", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SC", "alpha3code": "SYC", "prefix": "248", "name": "Seychelles", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SL", "alpha3code": "SLE", "prefix": "232", "name": "Sierra Leone", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SG", "alpha3code": "SGP", "prefix": "65", "name": "Singapore", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SK", "alpha3code": "SVK", "prefix": "421", "name": "Slovakia", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "20.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "SI", "alpha3code": "SVN", "prefix": "386", "name": "Slovenia", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "22.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "SB", "alpha3code": "SLB", "prefix": "677", "name": "Solomon Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SO", "alpha3code": "SOM", "prefix": "252", "name": "Somalia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ZA", "alpha3code": "ZAF", "prefix": "27", "name": "South Africa", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KR", "alpha3code": "KOR", "prefix": "82", "name": "South Korea", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SS", "alpha3code": "SSD", "prefix": "211", "name": "South Sudan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ES", "alpha3code": "ESP", "prefix": "34", "name": "Spain", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "21.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "LK", "alpha3code": "LKA", "prefix": "94", "name": "Sri Lanka", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "KN", "alpha3code": "KNA", "prefix": "1869", "name": "St. Kitts & Nevis", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "LC", "alpha3code": "LCA", "prefix": "1758", "name": "St. Lucia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SX", "alpha3code": "SXM", "prefix": "1721", "name": "St. Maarten", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "PM", "alpha3code": "SPM", "prefix": "508", "name": "St. Pierre and Miquelon", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "VC", "alpha3code": "VCT", "prefix": "1784", "name": "St. Vincent and the Grenadines", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SD", "alpha3code": "SDN", "prefix": "249", "name": "Sudan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SR", "alpha3code": "SUR", "prefix": "597", "name": "Suriname", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SZ", "alpha3code": "SWZ", "prefix": "268", "name": "Swaziland", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "SE", "alpha3code": "SWE", "prefix": "46", "name": "Sweden", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "25.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "CH", "alpha3code": "CHE", "prefix": "41", "name": "Switzerland", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "SY", "alpha3code": "SYR", "prefix": "963", "name": "Syria", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TW", "alpha3code": "TWN", "prefix": "886", "name": "Taiwan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TJ", "alpha3code": "TJK", "prefix": "992", "name": "Tajikistan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TZ", "alpha3code": "TZA", "prefix": "255", "name": "Tanzania", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "RT", "alpha3code": "RTD", "prefix": "1", "name": "Telecommunications for Disaster Relief", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TH", "alpha3code": "THU", "prefix": "66", "name": "Thailand", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TU", "alpha3code": "TUY", "prefix": "88216", "name": "Thuraya", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TL", "alpha3code": "TLS", "prefix": "670", "name": "Timor-Leste", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TG", "alpha3code": "TGO", "prefix": "228", "name": "Togo", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TK", "alpha3code": "TKL", "prefix": "690", "name": "Tokelau", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TO", "alpha3code": "TON", "prefix": "676", "name": "Tonga", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TT", "alpha3code": "TTO", "prefix": "1868", "name": "Trinidad And Tobago", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TN", "alpha3code": "TUN", "prefix": "216", "name": "Tunisia", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TR", "alpha3code": "TUR", "prefix": "90", "name": "Turkey", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TM", "alpha3code": "TKM", "prefix": "993", "name": "Turkmenistan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TC", "alpha3code": "TCA", "prefix": "1649", "name": "Turks And Caicos Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "TV", "alpha3code": "TUV", "prefix": "688", "name": "Tuvalu", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "UG", "alpha3code": "UGA", "prefix": "256", "name": "Uganda", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "UA", "alpha3code": "UKR", "prefix": "380", "name": "Ukraine", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "AE", "alpha3code": "ARE", "prefix": "971", "name": "United Arab Emirates", "iban": "Y", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "GB", "alpha3code": "GBR", "prefix": "44", "name": "United Kingdom", "iban": "Y", "account": "N", "vat": "Y", "vat_rate": "20.00", "sepa": "Y", "blacklisted": "N" },
      { "code": "US", "alpha3code": "USA", "prefix": "1", "name": "United States", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "UT", "alpha3code": "UTS", "prefix": "1", "name": "Universal Personal Telecommunication Service", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "UP", "alpha3code": "UPT", "prefix": "878", "name": "UPT", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "UY", "alpha3code": "URY", "prefix": "598", "name": "Uruguay", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "VI", "alpha3code": "VIR", "prefix": "1340", "name": "US Virgin Islands", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "UZ", "alpha3code": "UZB", "prefix": "998", "name": "Uzbekistan", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "VU", "alpha3code": "VUT", "prefix": "678", "name": "Vanuatu", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "VE", "alpha3code": "VEN", "prefix": "58", "name": "Venezuela", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "VN", "alpha3code": "VNM", "prefix": "84", "name": "Vietnam", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "WF", "alpha3code": "WLF", "prefix": "681", "name": "Wallis And Futuna", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "YE", "alpha3code": "YEM", "prefix": "967", "name": "Yemen", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ZM", "alpha3code": "ZMB", "prefix": "260", "name": "Zambia", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" },
      { "code": "ZW", "alpha3code": "ZWE", "prefix": "263", "name": "Zimbabwe", "iban": "N", "account": "N", "vat": "N", "vat_rate": "0.00", "sepa": "N", "blacklisted": "N" }
   ]